import { StatusType } from '@/components/KpiStatusCard';

// Mock KPI Data
export const mockIncidentKpis = [
  {
    title: 'Total Incidents',
    currentValue: 28,
    targetValue: 0,
    status: 'red' as StatusType,
    unit: '',
    change: -3,
    description: 'Total number of reported incidents in current period',
    tooltipText: 'Target is zero incidents. Any incident requires attention.',
  },
  {
    title: 'Incident Rate',
    currentValue: 2.4,
    targetValue: 2.0,
    status: 'yellow' as StatusType,
    unit: '%',
    change: -0.3,
    description: 'Number of recordable incidents per 100 full-time employees',
    tooltipText: 'Target is below 2.0%. Current status requires attention.',
  },
  {
    title: 'Near Misses',
    currentValue: 45,
    targetValue: 'N/A',
    status: 'neutral' as StatusType,
    unit: '',
    change: 5,
    description: 'Near miss reports (potential incidents that did not occur)',
    tooltipText: 'No specific target, but tracked for prevention insights.',
  },
  {
    title: 'Avg. Closure Time',
    currentValue: 12.5,
    targetValue: 10,
    status: 'yellow' as StatusType,
    unit: ' days',
    change: -2.3,
    description: 'Average time to close incident investigations',
    tooltipText: 'Target is 10 days or less. Improving from previous period.',
  },
];

export const mockDriverKpis = [
  {
    title: 'Average Safety Score',
    currentValue: 92,
    targetValue: 95,
    status: 'yellow' as StatusType,
    unit: '',
    change: 3,
    description: 'Average Samsara driver safety score across all drivers',
    tooltipText: 'Target is 95 or above. Based on driving habits from Samsara.',
  },
  {
    title: 'Speeding Events',
    currentValue: 32,
    targetValue: 20,
    status: 'red' as StatusType,
    unit: '',
    change: -5,
    description: 'Total number of speeding events in current period',
    tooltipText: 'Target is below 20 events. Improving from previous period.',
  },
  {
    title: 'Harsh Events',
    currentValue: 18,
    targetValue: 15,
    status: 'yellow' as StatusType,
    unit: '',
    change: -7,
    description: 'Total harsh acceleration, braking, and turning events',
    tooltipText: 'Target is 15 or fewer events. Significant improvement from last period.',
  },
  {
    title: 'Distracted Driving',
    currentValue: 5,
    targetValue: 0,
    status: 'red' as StatusType,
    unit: '',
    change: -2,
    description: 'Instances of detected distracted driving',
    tooltipText: 'Target is zero events. Any distracted driving requires attention.',
  },
];

export const mockComplianceKpis = [
  {
    title: 'Overall Compliance',
    currentValue: 94.5,
    targetValue: 100,
    status: 'yellow' as StatusType,
    unit: '%',
    change: 2.3,
    description: 'Overall regulatory compliance score across all departments',
    tooltipText: 'Target is 100%. Current score shows improvement from last period.',
  },
  {
    title: 'Audit Readiness',
    currentValue: 92,
    targetValue: 95,
    status: 'yellow' as StatusType,
    unit: '%',
    change: 3,
    description: 'Preparedness for regulatory compliance audits',
    tooltipText: 'Target is 95% or above. Based on document completeness and protocol adherence.',
  },
  {
    title: 'Open Violations',
    currentValue: 2,
    targetValue: 0,
    status: 'red' as StatusType,
    unit: '',
    change: -3,
    description: 'Number of unresolved regulatory violations',
    tooltipText: 'Target is zero violations. Improvement from 5 violations in previous period.',
  },
  {
    title: 'Upcoming Deadlines',
    currentValue: 6,
    targetValue: 'N/A',
    status: 'neutral' as StatusType,
    unit: '',
    change: 0,
    description: 'Regulatory filings due in next 30 days',
    tooltipText: 'Informational metric to track upcoming compliance requirements.',
  },
];

export const mockTrainingKpis = [
  {
    title: 'Overall Completion',
    currentValue: 86.5,
    targetValue: 100,
    status: 'yellow' as StatusType,
    unit: '%',
    change: 3.2,
    description: 'Overall training completion rate across all employees',
    tooltipText: 'Target is 100%. Current score shows improvement from last quarter.',
  },
  {
    title: 'Certification Rate',
    currentValue: 92,
    targetValue: 95,
    status: 'yellow' as StatusType,
    unit: '%',
    change: 5,
    description: 'Percentage of employees with up-to-date certifications',
    tooltipText: 'Target is 95% or above. Based on required certifications for roles.',
  },
  {
    title: 'Expiring Soon',
    currentValue: 12,
    targetValue: 'N/A',
    status: 'neutral' as StatusType,
    unit: '',
    change: -3,
    description: 'Certifications expiring in next 30 days',
    tooltipText: 'Informational metric to track upcoming certification renewals.',
  },
  {
    title: 'Overdue Training',
    currentValue: 8,
    targetValue: 0,
    status: 'red' as StatusType,
    unit: '',
    change: -4,
    description: 'Number of overdue training modules or certifications',
    tooltipText: 'Target is zero overdue items. Improvement from 12 last month.',
  },
];

// Mock Chart Data
export const mockIncidentTrendData = {
  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
  datasets: [
    {
      label: 'Recordable Incidents',
      data: [5, 3, 6, 4, 2, 8],
      backgroundColor: 'rgba(239, 68, 68, 0.5)',
      borderColor: 'rgb(239, 68, 68)',
      borderWidth: 1,
    },
    {
      label: 'Near Misses',
      data: [12, 9, 15, 11, 7, 10],
      backgroundColor: 'rgba(249, 115, 22, 0.5)',
      borderColor: 'rgb(249, 115, 22)',
      borderWidth: 1,
    },
  ],
};

export const mockIncidentTypeData = {
  labels: ['Vehicle Accident', 'Property Damage', 'Injury', 'Near Miss', 'Other'],
  datasets: [
    {
      label: 'Incident Types',
      data: [8, 5, 12, 45, 3],
      backgroundColor: [
        'rgba(239, 68, 68, 0.7)',
        'rgba(249, 115, 22, 0.7)',
        'rgba(234, 179, 8, 0.7)',
        'rgba(16, 185, 129, 0.7)',
        'rgba(99, 102, 241, 0.7)',
      ],
      borderColor: [
        'rgb(239, 68, 68)',
        'rgb(249, 115, 22)',
        'rgb(234, 179, 8)',
        'rgb(16, 185, 129)',
        'rgb(99, 102, 241)',
      ],
      borderWidth: 1,
    },
  ],
};

export const mockSafetyScoreTrendData = {
  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
  datasets: [
    {
      label: 'Average Safety Score',
      data: [86, 88, 87, 90, 91, 92],
      backgroundColor: 'rgba(52, 211, 153, 0.2)',
      borderColor: 'rgb(52, 211, 153)',
      borderWidth: 2,
      tension: 0.3,
      fill: true,
    },
    {
      label: 'Target',
      data: [95, 95, 95, 95, 95, 95],
      backgroundColor: 'rgba(0, 0, 0, 0)',
      borderColor: 'rgba(0, 0, 0, 0.2)',
      borderWidth: 2,
      borderDash: [5, 5],
    },
  ],
};

export const mockDrivingEventsData = {
  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
  datasets: [
    {
      label: 'Speeding Events',
      data: [42, 38, 35, 30, 36, 32],
      backgroundColor: 'rgba(239, 68, 68, 0.7)',
      borderColor: 'rgb(239, 68, 68)',
    },
    {
      label: 'Harsh Acceleration',
      data: [15, 12, 10, 9, 7, 8],
      backgroundColor: 'rgba(249, 115, 22, 0.7)',
      borderColor: 'rgb(249, 115, 22)',
    },
    {
      label: 'Harsh Braking',
      data: [18, 14, 12, 10, 8, 7],
      backgroundColor: 'rgba(234, 179, 8, 0.7)',
      borderColor: 'rgb(234, 179, 8)',
    },
    {
      label: 'Harsh Turning',
      data: [8, 7, 6, 5, 4, 3],
      backgroundColor: 'rgba(16, 185, 129, 0.7)',
      borderColor: 'rgb(16, 185, 129)',
    },
    {
      label: 'Distracted Driving',
      data: [12, 10, 8, 7, 6, 5],
      backgroundColor: 'rgba(99, 102, 241, 0.7)',
      borderColor: 'rgb(99, 102, 241)',
    },
  ],
};

export const mockComplianceTrendData = {
  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
  datasets: [
    {
      label: 'Overall Compliance %',
      data: [87, 88, 90, 92, 93, 94.5],
      backgroundColor: 'rgba(52, 211, 153, 0.2)',
      borderColor: 'rgb(52, 211, 153)',
      borderWidth: 2,
      tension: 0.3,
      fill: true,
    },
    {
      label: 'Target',
      data: [100, 100, 100, 100, 100, 100],
      backgroundColor: 'rgba(0, 0, 0, 0)',
      borderColor: 'rgba(0, 0, 0, 0.2)',
      borderWidth: 2,
      borderDash: [5, 5],
    },
  ],
};

export const mockDepartmentComplianceData = {
  labels: ['Operations', 'Maintenance', 'Safety', 'HR', 'Administration', 'Logistics'],
  datasets: [
    {
      label: 'Compliance %',
      data: [97, 92, 96, 98, 95, 91],
      backgroundColor: [
        'rgba(52, 211, 153, 0.7)',
        'rgba(250, 204, 21, 0.7)',
        'rgba(56, 189, 248, 0.7)',
        'rgba(167, 139, 250, 0.7)',
        'rgba(251, 146, 60, 0.7)',
        'rgba(251, 113, 133, 0.7)',
      ],
      borderColor: [
        'rgb(52, 211, 153)',
        'rgb(250, 204, 21)',
        'rgb(56, 189, 248)',
        'rgb(167, 139, 250)',
        'rgb(251, 146, 60)',
        'rgb(251, 113, 133)',
      ],
      borderWidth: 1,
    },
  ],
};

export const mockTrainingCompletionTrendData = {
  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
  datasets: [
    {
      label: 'Completion Rate %',
      data: [79, 81, 82, 84, 85, 86.5],
      backgroundColor: 'rgba(52, 211, 153, 0.2)',
      borderColor: 'rgb(52, 211, 153)',
      borderWidth: 2,
      tension: 0.3,
      fill: true,
    },
    {
      label: 'Target',
      data: [100, 100, 100, 100, 100, 100],
      backgroundColor: 'rgba(0, 0, 0, 0)',
      borderColor: 'rgba(0, 0, 0, 0.2)',
      borderWidth: 2,
      borderDash: [5, 5],
    },
  ],
};

export const mockDepartmentTrainingData = {
  labels: ['Operations', 'Maintenance', 'Safety', 'HR', 'Administration', 'Logistics'],
  datasets: [
    {
      label: 'Completion Rate %',
      data: [90, 82, 95, 98, 88, 79],
      backgroundColor: [
        'rgba(52, 211, 153, 0.7)',
        'rgba(250, 204, 21, 0.7)',
        'rgba(56, 189, 248, 0.7)',
        'rgba(167, 139, 250, 0.7)',
        'rgba(251, 146, 60, 0.7)',
        'rgba(251, 113, 133, 0.7)',
      ],
      borderColor: [
        'rgb(52, 211, 153)',
        'rgb(250, 204, 21)',
        'rgb(56, 189, 248)',
        'rgb(167, 139, 250)',
        'rgb(251, 146, 60)',
        'rgb(251, 113, 133)',
      ],
      borderWidth: 1,
    },
  ],
};

export const mockTrainingTypeData = {
  labels: ['Safety Training', 'Compliance', 'Technical Skills', 'Soft Skills', 'Leadership', 'Other'],
  datasets: [
    {
      label: 'Training Hours by Type',
      data: [42, 25, 18, 12, 8, 5],
      backgroundColor: [
        'rgba(239, 68, 68, 0.7)',
        'rgba(249, 115, 22, 0.7)',
        'rgba(234, 179, 8, 0.7)',
        'rgba(16, 185, 129, 0.7)',
        'rgba(99, 102, 241, 0.7)',
        'rgba(168, 85, 247, 0.7)',
      ],
      borderColor: [
        'rgb(239, 68, 68)',
        'rgb(249, 115, 22)',
        'rgb(234, 179, 8)',
        'rgb(16, 185, 129)',
        'rgb(99, 102, 241)',
        'rgb(168, 85, 247)',
      ],
      borderWidth: 1,
    },
  ],
};

// Mock Compliance Regulations Data
export const mockRegulations = [
  { 
    id: 'REG-001', 
    title: 'DOT Hours of Service Compliance',
    category: 'Operations',
    deadline: '2023-07-15',
    status: 'Compliant',
    responsibleParty: 'Operations Director',
    completionDate: '2023-05-28',
    notes: 'All driver logs verified and up to date. Electronic logging system fully implemented.',
    documents: 3,
  },
  { 
    id: 'REG-002', 
    title: 'Hazardous Materials Handling Certification',
    category: 'Safety',
    deadline: '2023-08-10',
    status: 'In Progress',
    responsibleParty: 'Safety Manager',
    completionDate: null,
    notes: 'Training scheduled for all relevant employees. 60% completed.',
    documents: 5,
  },
  { 
    id: 'REG-003', 
    title: 'Vehicle Maintenance Records',
    category: 'Maintenance',
    deadline: '2023-06-30',
    status: 'Attention Required',
    responsibleParty: 'Fleet Manager',
    completionDate: null,
    notes: 'Missing service records for 3 vehicles. Scheduled for completion by June 25.',
    documents: 2,
  },
  { 
    id: 'REG-004', 
    title: 'Driver Qualification Files',
    category: 'HR',
    deadline: '2023-07-01',
    status: 'Compliant',
    responsibleParty: 'HR Director',
    completionDate: '2023-06-10',
    notes: 'All driver files complete and up to date with required documentation.',
    documents: 8,
  },
  { 
    id: 'REG-005', 
    title: 'Drug & Alcohol Testing Program',
    category: 'Safety',
    deadline: '2023-06-15',
    status: 'Compliant',
    responsibleParty: 'Safety Manager',
    completionDate: '2023-06-01',
    notes: 'Random testing program ongoing. All records up to date.',
    documents: 4,
  },
  { 
    id: 'REG-006', 
    title: 'Environmental Compliance Audit',
    category: 'Administration',
    deadline: '2023-09-01',
    status: 'Not Started',
    responsibleParty: 'Compliance Officer',
    completionDate: null,
    notes: 'Scheduled to begin July 15. External auditor contracted.',
    documents: 0,
  },
  { 
    id: 'REG-007', 
    title: 'OSHA Safety Reporting',
    category: 'Safety',
    deadline: '2023-07-30',
    status: 'In Progress',
    responsibleParty: 'Safety Manager',
    completionDate: null,
    notes: 'Data collection underway. 75% complete.',
    documents: 6,
  },
  { 
    id: 'REG-008', 
    title: 'Commercial Driver\'s License Verification',
    category: 'HR',
    deadline: '2023-06-20',
    status: 'Compliant',
    responsibleParty: 'HR Director',
    completionDate: '2023-06-05',
    notes: 'All CDLs verified and documented. System set up for automatic expiration alerts.',
    documents: 3,
  },
];

// Mock KPI Goals Data
export const mockKpiGoals = [
  {
    id: 'kpi-001',
    metricName: 'Preventable Incidents',
    description: 'Number of preventable incidents per month',
    targetValue: 0,
    yellowThreshold: 2,
    redThreshold: 5,
    unit: 'incidents',
    division: 'All',
    plant: 'All',
    applicableTo: 'Company',
    effectiveDate: '2025-01-01',
    expirationDate: '2025-12-31',
    currentValue: 3,
    status: 'yellow',
  },
  {
    id: 'kpi-002',
    metricName: 'Average Safety Score',
    description: 'Average driver safety score across fleet',
    targetValue: 95,
    yellowThreshold: 90,
    redThreshold: 85,
    unit: 'score',
    division: 'Operations',
    plant: 'All',
    applicableTo: 'Drivers',
    effectiveDate: '2025-01-01',
    expirationDate: '2025-12-31',
    currentValue: 92,
    status: 'yellow',
  },
  {
    id: 'kpi-003',
    metricName: 'Training Compliance',
    description: 'Percentage of employees with up-to-date training',
    targetValue: 100,
    yellowThreshold: 95,
    redThreshold: 90,
    unit: '%',
    division: 'All',
    plant: 'All',
    applicableTo: 'All Employees',
    effectiveDate: '2025-01-01',
    expirationDate: '2025-12-31',
    currentValue: 96,
    status: 'yellow',
  },
  {
    id: 'kpi-004',
    metricName: 'Speeding Events',
    description: 'Number of speeding events per week',
    targetValue: 0,
    yellowThreshold: 10,
    redThreshold: 20,
    unit: 'events',
    division: 'Operations',
    plant: 'All',
    applicableTo: 'Drivers',
    effectiveDate: '2025-01-01',
    expirationDate: '2025-12-31',
    currentValue: 15,
    status: 'yellow',
  },
  {
    id: 'kpi-005',
    metricName: 'Harsh Driving Events',
    description: 'Number of harsh acceleration, braking, or turning events per week',
    targetValue: 5,
    yellowThreshold: 15,
    redThreshold: 30,
    unit: 'events',
    division: 'Operations',
    plant: 'All',
    applicableTo: 'Drivers',
    effectiveDate: '2025-01-01',
    expirationDate: '2025-12-31',
    currentValue: 12,
    status: 'green',
  },
  {
    id: 'kpi-006',
    metricName: 'Incident Investigation Completion',
    description: 'Percentage of incident investigations completed within 7 days',
    targetValue: 100,
    yellowThreshold: 90,
    redThreshold: 80,
    unit: '%',
    division: 'Safety',
    plant: 'All',
    applicableTo: 'Safety Team',
    effectiveDate: '2025-01-01',
    expirationDate: '2025-12-31',
    currentValue: 85,
    status: 'yellow',
  },
  {
    id: 'kpi-007',
    metricName: 'Vehicle Inspection Compliance',
    description: 'Percentage of vehicle inspections completed on time',
    targetValue: 100,
    yellowThreshold: 95,
    redThreshold: 90,
    unit: '%',
    division: 'Maintenance',
    plant: 'All',
    applicableTo: 'Maintenance Team',
    effectiveDate: '2025-01-01',
    expirationDate: '2025-12-31',
    currentValue: 98,
    status: 'green',
  },
  {
    id: 'kpi-008',
    metricName: 'Safety Meeting Attendance',
    description: 'Percentage of employees attending monthly safety meetings',
    targetValue: 100,
    yellowThreshold: 90,
    redThreshold: 80,
    unit: '%',
    division: 'All',
    plant: 'All',
    applicableTo: 'All Employees',
    effectiveDate: '2025-01-01',
    expirationDate: '2025-12-31',
    currentValue: 92,
    status: 'yellow',
  },
  {
    id: 'kpi-009',
    metricName: 'Near Miss Reporting',
    description: 'Number of near misses reported per month',
    targetValue: 10,
    yellowThreshold: 5,
    redThreshold: 2,
    unit: 'reports',
    division: 'All',
    plant: 'All',
    applicableTo: 'All Employees',
    effectiveDate: '2025-01-01',
    expirationDate: '2025-12-31',
    currentValue: 8,
    status: 'yellow',
  },
  {
    id: 'kpi-010',
    metricName: 'Safety Audit Score',
    description: 'Average score on monthly safety audits',
    targetValue: 100,
    yellowThreshold: 90,
    redThreshold: 80,
    unit: '%',
    division: 'All',
    plant: 'All',
    applicableTo: 'Company',
    effectiveDate: '2025-01-01',
    expirationDate: '2025-12-31',
    currentValue: 94,
    status: 'yellow',
  },
  {
    id: 'kpi-011',
    metricName: 'Distracted Driving Events',
    description: 'Number of distracted driving events per week',
    targetValue: 0,
    yellowThreshold: 5,
    redThreshold: 10,
    unit: 'events',
    division: 'Operations',
    plant: 'All',
    applicableTo: 'Drivers',
    effectiveDate: '2025-01-01',
    expirationDate: '2025-12-31',
    currentValue: 3,
    status: 'yellow',
  },
  {
    id: 'kpi-012',
    metricName: 'Compliance Violations',
    description: 'Number of regulatory compliance violations per quarter',
    targetValue: 0,
    yellowThreshold: 1,
    redThreshold: 3,
    unit: 'violations',
    division: 'All',
    plant: 'All',
    applicableTo: 'Company',
    effectiveDate: '2025-01-01',
    expirationDate: '2025-12-31',
    currentValue: 0,
    status: 'green',
  },
];

// Mock Users Data
export const mockUsers = [
  {
    id: 'user-001',
    name: 'John Doe',
    email: 'john.doe@example.com',
    role: 'Admin',
    department: 'Safety',
    status: 'Active',
    lastLogin: '2025-06-25 09:15 AM',
    createdAt: '2025-01-15',
  },
  {
    id: 'user-002',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    role: 'Manager',
    department: 'Operations',
    status: 'Active',
    lastLogin: '2025-06-26 11:32 AM',
    createdAt: '2025-01-20',
  },
  {
    id: 'user-003',
    name: 'Robert Johnson',
    email: 'robert.johnson@example.com',
    role: 'Viewer',
    department: 'Maintenance',
    status: 'Active',
    lastLogin: '2025-06-24 03:45 PM',
    createdAt: '2025-02-05',
  },
  {
    id: 'user-004',
    name: 'Sarah Williams',
    email: 'sarah.williams@example.com',
    role: 'Manager',
    department: 'HR',
    status: 'Inactive',
    lastLogin: '2025-05-30 10:20 AM',
    createdAt: '2025-02-10',
  },
  {
    id: 'user-005',
    name: 'Michael Brown',
    email: 'michael.brown@example.com',
    role: 'Viewer',
    department: 'Operations',
    status: 'Active',
    lastLogin: '2025-06-26 09:05 AM',
    createdAt: '2025-02-15',
  },
  {
    id: 'user-006',
    name: 'Emily Davis',
    email: 'emily.davis@example.com',
    role: 'Manager',
    department: 'Safety',
    status: 'Active',
    lastLogin: '2025-06-25 01:40 PM',
    createdAt: '2025-03-01',
  },
  {
    id: 'user-007',
    name: 'David Wilson',
    email: 'david.wilson@example.com',
    role: 'Viewer',
    department: 'Finance',
    status: 'Active',
    lastLogin: '2025-06-26 08:55 AM',
    createdAt: '2025-03-10',
  },
  {
    id: 'user-008',
    name: 'Jennifer Moore',
    email: 'jennifer.moore@example.com',
    role: 'Admin',
    department: 'IT',
    status: 'Active',
    lastLogin: '2025-06-26 10:15 AM',
    createdAt: '2025-03-15',
  },
  {
    id: 'user-009',
    name: 'Christopher Taylor',
    email: 'christopher.taylor@example.com',
    role: 'Viewer',
    department: 'Operations',
    status: 'Inactive',
    lastLogin: '2025-06-01 11:30 AM',
    createdAt: '2025-04-01',
  },
  {
    id: 'user-010',
    name: 'Amanda Anderson',
    email: 'amanda.anderson@example.com',
    role: 'Manager',
    department: 'Maintenance',
    status: 'Active',
    lastLogin: '2025-06-25 02:25 PM',
    createdAt: '2025-04-10',
  },
  {
    id: 'user-011',
    name: 'Matthew Thomas',
    email: 'matthew.thomas@example.com',
    role: 'Viewer',
    department: 'HR',
    status: 'Active',
    lastLogin: '2025-06-24 09:50 AM',
    createdAt: '2025-04-15',
  },
  {
    id: 'user-012',
    name: 'Olivia Jackson',
    email: 'olivia.jackson@example.com',
    role: 'Viewer',
    department: 'Safety',
    status: 'Active',
    lastLogin: '2025-06-25 11:05 AM',
    createdAt: '2025-05-01',
  },
  {
    id: 'user-013',
    name: 'Daniel White',
    email: 'daniel.white@example.com',
    role: 'Manager',
    department: 'Operations',
    status: 'Active',
    lastLogin: '2025-06-26 09:30 AM',
    createdAt: '2025-05-10',
  },
  {
    id: 'user-014',
    name: 'Sophia Harris',
    email: 'sophia.harris@example.com',
    role: 'Viewer',
    department: 'Finance',
    status: 'Inactive',
    lastLogin: '2025-05-15 10:40 AM',
    createdAt: '2025-05-15',
  },
  {
    id: 'user-015',
    name: 'James Martin',
    email: 'james.martin@example.com',
    role: 'Admin',
    department: 'IT',
    status: 'Active',
    lastLogin: '2025-06-26 08:20 AM',
    createdAt: '2025-06-01',
  },
  {
    id: 'user-016',
    name: 'Isabella Thompson',
    email: 'isabella.thompson@example.com',
    role: 'Manager',
    department: 'Safety',
    status: 'Active',
    lastLogin: '2025-06-25 03:30 PM',
    createdAt: '2025-06-05',
  },
  {
    id: 'user-017',
    name: 'William Garcia',
    email: 'william.garcia@example.com',
    role: 'Viewer',
    department: 'Operations',
    status: 'Active',
    lastLogin: '2025-06-24 01:15 PM',
    createdAt: '2025-06-10',
  },
  {
    id: 'user-018',
    name: 'Mia Martinez',
    email: 'mia.martinez@example.com',
    role: 'Viewer',
    department: 'Maintenance',
    status: 'Active',
    lastLogin: '2025-06-25 10:50 AM',
    createdAt: '2025-06-15',
  },
  {
    id: 'user-019',
    name: 'Benjamin Robinson',
    email: 'benjamin.robinson@example.com',
    role: 'Manager',
    department: 'HR',
    status: 'Active',
    lastLogin: '2025-06-26 11:10 AM',
    createdAt: '2025-06-20',
  },
  {
    id: 'user-020',
    name: 'Charlotte Clark',
    email: 'charlotte.clark@example.com',
    role: 'Viewer',
    department: 'Finance',
    status: 'Active',
    lastLogin: '2025-06-25 04:00 PM',
    createdAt: '2025-06-22',
  },
];
